# Generated by Django 2.2.2 on 2019-06-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, upload_to='employee/year-%Y/month-%m/day-%d'),
        ),
    ]
