# Generated by Django 2.2.2 on 2019-06-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20190626_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='about',
            field=models.TextField(blank=True, verbose_name='History'),
        ),
    ]
