# Generated by Django 2.2.2 on 2019-06-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='about',
            field=models.TextField(verbose_name='History'),
        ),
    ]
