# Generated by Django 2.2.2 on 2019-06-28 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_auto_20190627_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
