# Generated by Django 2.2.2 on 2019-06-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_hire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='rating',
            field=models.DecimalField(auto_created=True, decimal_places=1, default=10.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is it active?'),
        ),
    ]
