# Generated by Django 2.2.2 on 2019-06-27 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_auto_20190627_1245'),
        ('certificates', '0003_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Employee'),
        ),
    ]
