# Generated by Django 2.2.2 on 2019-06-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
