# Generated by Django 2.2.2 on 2019-06-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_auto_20190628_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.BooleanField(verbose_name='is good?'),
        ),
    ]
